services:
  - type: web
    name: anki-web
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: |
      mkdir -p instance
      export FLASK_APP=app.py
      python -m flask db upgrade
      gunicorn app:app
    envVars:
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: API_KEY
        generateValue: true
      - key: DATABASE_URL
        value: sqlite:///prod.db
      - key: FLASK_APP
        value: app.py